import { User } from '../types/user';
import { Instrument } from '../types/instrument';
import { Application } from '../types/application';
import { Inspection } from '../types/inspection';
import { Certificate } from '../types/certificate';
import { Notification, RenewalAlert, AuditLog } from '../types/notification';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_applicant_1',
    name: 'Rajesh Sharma',
    email: 'applicant@metroverify.gov.in',
    role: 'applicant',
    phone: '+91 98765 43210',
    organization: 'Apex Agro & Logistics Hub Ltd',
    designation: 'Managing Director & Authorized Signatory',
    address: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi - 110020',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-01-10T10:00:00Z'
  },
  {
    id: 'usr_officer_1',
    name: 'Inspector S. K. Verma',
    email: 'officer@metroverify.gov.in',
    role: 'officer',
    phone: '+91 98111 22334',
    organization: 'Directorate of Legal Metrology',
    designation: 'Senior Legal Metrology Inspector',
    badgeNumber: 'LMI-DL-2018-044',
    jurisdictionZone: 'North & Central Delhi Zone 2',
    address: 'Legal Metrology Bhawan, ITO, New Delhi - 110002',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-06-15T09:30:00Z'
  },
  {
    id: 'usr_officer_2',
    name: 'Inspector Priya Deshmukh',
    email: 'priya.officer@metroverify.gov.in',
    role: 'officer',
    phone: '+91 98222 33445',
    organization: 'Directorate of Legal Metrology',
    designation: 'Assistant Controller & Field Inspector',
    badgeNumber: 'LMI-DL-2020-089',
    jurisdictionZone: 'South Delhi Industrial Zone 4',
    address: 'Sub-Divisional Legal Metrology Office, Okhla, New Delhi',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-08-20T11:00:00Z'
  },
  {
    id: 'usr_admin_1',
    name: 'Dr. A. Ramanathan',
    email: 'admin@metroverify.gov.in',
    role: 'admin',
    phone: '+91 99000 11223',
    organization: 'Ministry of Consumer Affairs & Legal Metrology',
    designation: 'Controller & Chief Verification Officer',
    badgeNumber: 'CLM-HQ-001',
    jurisdictionZone: 'National Jurisdiction / All Zones',
    address: 'Krishi Bhawan, Dr. Rajendra Prasad Road, New Delhi - 110001',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2024-01-01T08:00:00Z'
  }
];

export const INITIAL_INSTRUMENTS: Instrument[] = [
  {
    id: 'INST-2026-001',
    name: 'Heavy Duty Pitless Electronic Weighbridge',
    type: 'Electronic Weighbridge',
    manufacturer: 'Avery Weigh-Tronix India Pvt Ltd',
    modelNumber: 'BridgeMaster Pro-60T',
    serialNumber: 'AWT-WB-2023-9981',
    capacity: '60,000 kg x 10 kg',
    accuracyClass: 'Class III (Medium)',
    yearOfManufacture: 2023,
    installationLocation: 'Main Gate Weigh Station, Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    purposeOfUse: 'Industrial Logistics',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    previousCertificateNumber: 'MV-CERT-2025-4122',
    previousVerificationDate: '2025-10-10',
    expiryDate: '2026-10-10',
    status: 'Pending Re-verification',
    currentCertificateId: 'CERT-2025-001',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z'
  },
  {
    id: 'INST-2026-002',
    name: 'High Precision Analytical Gold & Gem Balance',
    type: 'Non-Automatic Weighing Instrument (NAWI)',
    manufacturer: 'Sartorius Lab Instruments GmbH',
    modelNumber: 'Secura 224-1S',
    serialNumber: 'SAR-SEC-2024-4412',
    capacity: '220 g x 0.1 mg',
    accuracyClass: 'Class I (Special)',
    yearOfManufacture: 2024,
    installationLocation: 'Bullion Vault Assay Lab, Connaught Place, New Delhi',
    purposeOfUse: 'Gold & Precious Metals',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    previousCertificateNumber: 'MV-CERT-2026-9041',
    previousVerificationDate: '2026-02-15',
    expiryDate: '2027-02-14',
    status: 'Active',
    currentCertificateId: 'CERT-2026-001',
    createdAt: '2025-02-01T14:30:00Z',
    updatedAt: '2026-02-15T16:00:00Z'
  },
  {
    id: 'INST-2026-003',
    name: 'Multi-Product Electronic Fuel Dispenser',
    type: 'Fuel Dispenser (MPD)',
    manufacturer: 'Gilbarco Veeder-Root India',
    modelNumber: 'Horizon 4-Hose High Flow',
    serialNumber: 'GVR-MPD-2024-8871',
    capacity: '50 L/min (Accuracy +/- 0.3%)',
    accuracyClass: 'Class III (Medium)',
    yearOfManufacture: 2024,
    installationLocation: 'Island #3, Highway Retail Fuel Station, NH-48 Express Corridor',
    purposeOfUse: 'Petroleum & Gas',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    status: 'Under Verification',
    createdAt: '2025-05-10T09:00:00Z',
    updatedAt: '2026-09-12T11:00:00Z'
  },
  {
    id: 'INST-2026-004',
    name: 'Stainless Steel Commercial Platform Scale',
    type: 'Platform Scale',
    manufacturer: 'Essae-Teraoka Pvt Ltd',
    modelNumber: 'DS-215 Waterproof Platform',
    serialNumber: 'ESS-DS215-2025-331',
    capacity: '150 kg x 10 g',
    accuracyClass: 'Class III (Medium)',
    yearOfManufacture: 2025,
    installationLocation: 'Packaging Dock Section A, Warehouse 3, New Delhi',
    purposeOfUse: 'Commercial Retail',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    status: 'Under Verification',
    createdAt: '2026-01-20T10:15:00Z',
    updatedAt: '2026-09-15T09:00:00Z'
  },
  {
    id: 'INST-2026-005',
    name: 'High-Speed Inline Checkweigher',
    type: 'Automatic Catchweigher',
    manufacturer: 'Mettler Toledo Industrial',
    modelNumber: 'Garvens C3530',
    serialNumber: 'MT-CW-2023-772',
    capacity: '5 kg x 1 g',
    accuracyClass: 'Class III (Medium)',
    yearOfManufacture: 2023,
    installationLocation: 'Conveyor Line 2, Packaging Section B, New Delhi',
    purposeOfUse: 'Industrial Logistics',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    status: 'Expired',
    previousCertificateNumber: 'MV-CERT-2024-1090',
    previousVerificationDate: '2024-08-01',
    expiryDate: '2025-08-01',
    createdAt: '2024-03-01T11:00:00Z',
    updatedAt: '2025-08-02T10:00:00Z'
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'APP-2026-0842',
    instrumentId: 'INST-2026-004',
    instrumentName: 'Stainless Steel Commercial Platform Scale',
    instrumentType: 'Platform Scale',
    serialNumber: 'ESS-DS215-2025-331',
    capacity: '150 kg x 10 g',
    location: 'Packaging Dock Section A, Warehouse 3, New Delhi',
    ownerId: 'usr_applicant_1',
    ownerName: 'Rajesh Sharma (Apex Agro)',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    applicationDate: '2026-09-18',
    priority: 'Normal',
    status: 'Pending',
    feeAmount: 750,
    paymentStatus: 'Paid',
    trackingSteps: [
      { stepNumber: 1, title: 'Application Submitted', description: 'Application filed online and statutory fee credited.', status: 'Completed', date: '2026-09-18 10:15 AM', actor: 'Applicant' },
      { stepNumber: 2, title: 'Application Reviewed', description: 'Desk audit of documents in progress.', status: 'Current', date: '2026-09-19 11:30 AM', actor: 'Legal Metrology Desk' },
      { stepNumber: 3, title: 'Officer Assigned', description: 'Verification officer assignment pending.', status: 'Pending' },
      { stepNumber: 4, title: 'Inspection Scheduled', description: 'On-site verification date to be set.', status: 'Pending' },
      { stepNumber: 5, title: 'Field Inspection', description: 'On-site metrological tests and seal verification.', status: 'Pending' },
      { stepNumber: 6, title: 'Verification Completed', description: 'Inspection report and NAWI test sheet upload.', status: 'Pending' },
      { stepNumber: 7, title: 'Digital Approval', description: 'Scrutiny and digital sign-off by Controller.', status: 'Pending' },
      { stepNumber: 8, title: 'Certificate Generated', description: 'Issuance of official QR Certificate of Verification.', status: 'Pending' }
    ],
    createdAt: '2026-09-18T10:15:00Z',
    updatedAt: '2026-09-19T11:30:00Z'
  },
  {
    id: 'APP-2026-0841',
    instrumentId: 'INST-2026-001',
    instrumentName: 'Heavy Duty Pitless Electronic Weighbridge',
    instrumentType: 'Electronic Weighbridge',
    serialNumber: 'AWT-WB-2023-9981',
    capacity: '60,000 kg x 10 kg',
    location: 'Main Gate Weigh Station, Plot 44-B, MIDC Industrial Area, Phase II',
    ownerId: 'usr_applicant_1',
    ownerName: 'Rajesh Sharma (Apex Agro)',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    applicationDate: '2026-09-15',
    inspectionScheduledDate: '2026-09-24',
    officerId: 'usr_officer_1',
    officerName: 'Inspector S. K. Verma',
    officerBadge: 'LMI-DL-2018-044',
    priority: 'High',
    status: 'Inspection Scheduled',
    feeAmount: 4500,
    paymentStatus: 'Paid',
    trackingSteps: [
      { stepNumber: 1, title: 'Application Submitted', description: 'Renewal verification application submitted online.', status: 'Completed', date: '2026-09-15 09:30 AM', actor: 'Applicant' },
      { stepNumber: 2, title: 'Application Reviewed', description: 'Past certificate & installation drawings scrutinized.', status: 'Completed', date: '2026-09-16 02:15 PM', actor: 'Assistant Controller' },
      { stepNumber: 3, title: 'Officer Assigned', description: 'Assigned to Inspector S. K. Verma (Zone 2).', status: 'Completed', date: '2026-09-17 11:00 AM', actor: 'Admin Desk' },
      { stepNumber: 4, title: 'Inspection Scheduled', description: 'Scheduled for 24-Sep-2026 with test mobile weigh lorry.', status: 'Current', date: '2026-09-17 04:00 PM', actor: 'Inspector S. K. Verma' },
      { stepNumber: 5, title: 'Field Inspection', description: 'Eccentricity, Corner, Zero & Span tests on 60T load.', status: 'Pending' },
      { stepNumber: 6, title: 'Verification Completed', description: 'Formulation of NAWI inspection dossier.', status: 'Pending' },
      { stepNumber: 7, title: 'Digital Approval', description: 'Final Controller approval.', status: 'Pending' },
      { stepNumber: 8, title: 'Certificate Generated', description: 'New verification seal and QR Certificate.', status: 'Pending' }
    ],
    createdAt: '2026-09-15T09:30:00Z',
    updatedAt: '2026-09-17T16:00:00Z'
  },
  {
    id: 'APP-2026-0840',
    instrumentId: 'INST-2026-003',
    instrumentName: 'Multi-Product Electronic Fuel Dispenser',
    instrumentType: 'Fuel Dispenser (MPD)',
    serialNumber: 'GVR-MPD-2024-8871',
    capacity: '50 L/min (Accuracy +/- 0.3%)',
    location: 'Island #3, Highway Retail Fuel Station, NH-48 Express Corridor',
    ownerId: 'usr_applicant_1',
    ownerName: 'Rajesh Sharma (Apex Agro)',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    applicationDate: '2026-09-10',
    inspectionScheduledDate: '2026-09-14',
    inspectionCompletedDate: '2026-09-14',
    officerId: 'usr_officer_1',
    officerName: 'Inspector S. K. Verma',
    officerBadge: 'LMI-DL-2018-044',
    priority: 'Normal',
    status: 'Inspection Completed',
    inspectionId: 'INSP-2026-001',
    feeAmount: 2000,
    paymentStatus: 'Paid',
    trackingSteps: [
      { stepNumber: 1, title: 'Application Submitted', description: 'Mandatory annual fuel dispenser reverification filed.', status: 'Completed', date: '2026-09-10 10:00 AM' },
      { stepNumber: 2, title: 'Application Reviewed', description: 'Petroleum & Explosives Safety Organization (PESO) documents verified.', status: 'Completed', date: '2026-09-11 11:30 AM' },
      { stepNumber: 3, title: 'Officer Assigned', description: 'Inspector S. K. Verma assigned.', status: 'Completed', date: '2026-09-12 10:00 AM' },
      { stepNumber: 4, title: 'Inspection Scheduled', description: 'Inspection rostered for 14-Sep-2026.', status: 'Completed', date: '2026-09-12 03:00 PM' },
      { stepNumber: 5, title: 'Field Inspection', description: '5L & 10L volumetric standard flask tests executed. Dispensing error +0.08% within MPE (+/-0.3%).', status: 'Completed', date: '2026-09-14 01:30 PM' },
      { stepNumber: 6, title: 'Verification Completed', description: 'Field inspection passed. Test report submitted by Inspector.', status: 'Completed', date: '2026-09-14 04:00 PM' },
      { stepNumber: 7, title: 'Digital Approval', description: 'Pending final review and Controller digital stamp.', status: 'Current', note: 'Awaiting Admin sign-off' },
      { stepNumber: 8, title: 'Certificate Generated', description: 'Will be generated immediately upon Controller approval.', status: 'Pending' }
    ],
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-14T16:00:00Z'
  },
  {
    id: 'APP-2026-0839',
    instrumentId: 'INST-2026-002',
    instrumentName: 'High Precision Analytical Gold & Gem Balance',
    instrumentType: 'Non-Automatic Weighing Instrument (NAWI)',
    serialNumber: 'SAR-SEC-2024-4412',
    capacity: '220 g x 0.1 mg',
    location: 'Bullion Vault Assay Lab, Connaught Place, New Delhi',
    ownerId: 'usr_applicant_1',
    ownerName: 'Rajesh Sharma (Apex Agro)',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    applicationDate: '2026-02-10',
    inspectionScheduledDate: '2026-02-14',
    inspectionCompletedDate: '2026-02-14',
    approvalDate: '2026-02-15',
    officerId: 'usr_officer_2',
    officerName: 'Inspector Priya Deshmukh',
    officerBadge: 'LMI-DL-2020-089',
    priority: 'Normal',
    status: 'Approved',
    inspectionId: 'INSP-2026-002',
    certificateId: 'CERT-2026-001',
    certificateNumber: 'MV-CERT-2026-9041',
    feeAmount: 1500,
    paymentStatus: 'Paid',
    trackingSteps: [
      { stepNumber: 1, title: 'Application Submitted', description: 'Application received and processed.', status: 'Completed', date: '2026-02-10' },
      { stepNumber: 2, title: 'Application Reviewed', description: 'Model approval OIML R76 Certificate verified.', status: 'Completed', date: '2026-02-11' },
      { stepNumber: 3, title: 'Officer Assigned', description: 'Inspector Priya Deshmukh assigned.', status: 'Completed', date: '2026-02-12' },
      { stepNumber: 4, title: 'Inspection Scheduled', description: 'Field appointment booked.', status: 'Completed', date: '2026-02-13' },
      { stepNumber: 5, title: 'Field Inspection', description: 'Class E2 reference weight testing conducted.', status: 'Completed', date: '2026-02-14' },
      { stepNumber: 6, title: 'Verification Completed', description: 'Zero error 0.0 mg, repeatability 0.08 mg. Status PASS.', status: 'Completed', date: '2026-02-14' },
      { stepNumber: 7, title: 'Digital Approval', description: 'Approved by Dr. A. Ramanathan, Controller.', status: 'Completed', date: '2026-02-15' },
      { stepNumber: 8, title: 'Certificate Generated', description: 'Certificate MV-CERT-2026-9041 issued with QR verification.', status: 'Completed', date: '2026-02-15' }
    ],
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z'
  },
  {
    id: 'APP-2026-0838',
    instrumentId: 'INST-2026-005',
    instrumentName: 'High-Speed Inline Checkweigher',
    instrumentType: 'Automatic Catchweigher',
    serialNumber: 'MT-CW-2023-772',
    capacity: '5 kg x 1 g',
    location: 'Conveyor Line 2, Packaging Section B, New Delhi',
    ownerId: 'usr_applicant_1',
    ownerName: 'Rajesh Sharma (Apex Agro)',
    ownerPhone: '+91 98765 43210',
    ownerEmail: 'applicant@metroverify.gov.in',
    applicationDate: '2026-01-05',
    inspectionScheduledDate: '2026-01-10',
    inspectionCompletedDate: '2026-01-10',
    officerId: 'usr_officer_1',
    officerName: 'Inspector S. K. Verma',
    officerBadge: 'LMI-DL-2018-044',
    priority: 'Normal',
    status: 'Rejected',
    rejectionReason: 'Load cell sensor drift observed. Repeatability error exceeded MPE by 4.2g under dynamic belt speed test. Calibration repair required.',
    feeAmount: 1200,
    paymentStatus: 'Paid',
    trackingSteps: [
      { stepNumber: 1, title: 'Application Submitted', description: 'Application filed.', status: 'Completed', date: '2026-01-05' },
      { stepNumber: 2, title: 'Application Reviewed', description: 'Desk clearance granted.', status: 'Completed', date: '2026-01-06' },
      { stepNumber: 3, title: 'Officer Assigned', description: 'Inspector S. K. Verma designated.', status: 'Completed', date: '2026-01-07' },
      { stepNumber: 4, title: 'Inspection Scheduled', description: 'Physical test scheduled.', status: 'Completed', date: '2026-01-08' },
      { stepNumber: 5, title: 'Field Inspection', description: 'Testing identified excessive repeatability variation.', status: 'Completed', date: '2026-01-10' },
      { stepNumber: 6, title: 'Verification Completed', description: 'Result FAIL.', status: 'Completed', date: '2026-01-10' },
      { stepNumber: 7, title: 'Digital Approval', description: 'Application rejected due to statutory tolerance failure.', status: 'Completed', date: '2026-01-11' },
      { stepNumber: 8, title: 'Certificate Generated', description: 'Certificate withheld. Re-application needed post recalibration.', status: 'Pending' }
    ],
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-01-11T12:00:00Z'
  }
];

export const INITIAL_INSPECTIONS: Inspection[] = [
  {
    id: 'INSP-2026-001',
    applicationId: 'APP-2026-0840',
    instrumentId: 'INST-2026-003',
    officerId: 'usr_officer_1',
    officerName: 'Inspector S. K. Verma',
    officerBadge: 'LMI-DL-2018-044',
    inspectionDate: '2026-09-14',
    location: 'Island #3, Highway Retail Fuel Station, NH-48 Express Corridor',
    physical: {
      instrumentCondition: 'Good',
      manufacturerDetailsVerified: true,
      serialNumberVerified: true,
      sealCondition: 'Intact',
      displayCondition: 'Clear & Readable',
      levelIndicatorOk: true,
      leadAndWireSealAffixed: true,
      sealTagNumber: 'DL-LM-SEAL-88402'
    },
    measurement: {
      standardWeightsUsed: 'Standard 5-Litre & 10-Litre Conical Metal Provers (Cert # RRSL/FL/2026/012)',
      zeroLoadError: '0.00 Litres at cut-off valve',
      observedMeasurement: 'Delivery of 5.004 L on 5.000 L preset (+0.08%)',
      permissibleError: '+/- 0.3% (+/- 15 mL on 5 Litres as per Legal Metrology Rules)',
      repeatabilityResult: 'Satisfactory (Range < 1 e)',
      eccentricityTestResult: 'Pass (Corners within MPE)',
      accuracyTestResult: 'Pass',
      testLoadPoints: '5 Litres (Slow Delivery), 10 Litres (Fast Delivery 45 L/min)'
    },
    documentation: {
      modelApprovalVerified: true,
      modelApprovalNumber: 'IND/09/2022/411',
      previousCertificateVerified: true,
      userManualAvailable: true,
      taxInvoiceVerified: true
    },
    result: 'PASS',
    remarks: 'Totalizer reading recorded at 1,421,908 Litres. Security seal wire intact. Calibrated metering unit locked with official tamper-evident lead seal DL-LM-SEAL-88402. Verification passed.',
    photos: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=600&auto=format&fit=crop&q=80'
    ],
    status: 'Submitted',
    submittedAt: '2026-09-14T16:00:00Z'
  },
  {
    id: 'INSP-2026-002',
    applicationId: 'APP-2026-0839',
    instrumentId: 'INST-2026-002',
    officerId: 'usr_officer_2',
    officerName: 'Inspector Priya Deshmukh',
    officerBadge: 'LMI-DL-2020-089',
    inspectionDate: '2026-02-14',
    location: 'Bullion Vault Assay Lab, Connaught Place, New Delhi',
    physical: {
      instrumentCondition: 'Excellent',
      manufacturerDetailsVerified: true,
      serialNumberVerified: true,
      sealCondition: 'Intact',
      displayCondition: 'Clear & Readable',
      levelIndicatorOk: true,
      leadAndWireSealAffixed: true,
      sealTagNumber: 'DL-LM-SEAL-77914'
    },
    measurement: {
      standardWeightsUsed: 'National Physical Laboratory (NPL) Traceable Class E2 Standard Weights Set',
      zeroLoadError: '0.0000 g with tare compensation',
      observedMeasurement: '200.0001 g observed on 200.0000 g reference weight',
      permissibleError: '+/- 0.5 mg (+/- 0.0005 g) as per OIML R76 Class I',
      repeatabilityResult: 'Satisfactory (Range < 1 e)',
      eccentricityTestResult: 'Pass (Corners within MPE)',
      accuracyTestResult: 'Pass',
      testLoadPoints: '50g, 100g, 150g, 200g (Class I)'
    },
    documentation: {
      modelApprovalVerified: true,
      modelApprovalNumber: 'IND/01/2023/108',
      previousCertificateVerified: true,
      userManualAvailable: true,
      taxInvoiceVerified: true
    },
    result: 'PASS',
    remarks: 'Air draft shield intact. Anti-vibration granite table verified. Instrument passed all metrological tests under Legal Metrology Act 2009.',
    photos: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80'
    ],
    status: 'Reviewed',
    submittedAt: '2026-02-14T15:30:00Z'
  }
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'CERT-2026-001',
    certificateNumber: 'MV-CERT-2026-9041',
    applicationId: 'APP-2026-0839',
    instrumentId: 'INST-2026-002',
    instrumentName: 'High Precision Analytical Gold & Gem Balance',
    instrumentType: 'Non-Automatic Weighing Instrument (NAWI)',
    capacity: '220 g x 0.1 mg',
    accuracyClass: 'Class I (Special)',
    serialNumber: 'SAR-SEC-2024-4412',
    manufacturer: 'Sartorius Lab Instruments GmbH',
    modelNumber: 'Secura 224-1S',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd (Rajesh Sharma)',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi - 110020',
    installationLocation: 'Bullion Vault Assay Lab, Connaught Place, New Delhi',
    verificationDate: '2026-02-15',
    expiryDate: '2027-02-14',
    officerId: 'usr_officer_2',
    officerName: 'Inspector Priya Deshmukh',
    officerBadge: 'LMI-DL-2020-089',
    issuingAuthority: 'Department of Legal Metrology, Government of NCT of Delhi',
    jurisdictionZone: 'Central Delhi Zone 2',
    sealTagNumber: 'DL-LM-SEAL-77914',
    verificationFeePaid: 1500,
    status: 'VALID',
    digitalSignatureHash: 'SHA256:8f4c2e1b99a67d021c3b5f90a982ee3310f882ad34bb1c828941bc0091ef3e12',
    verificationUrl: '/verify/MV-CERT-2026-9041',
    qrPayload: 'https://metroverify360.gov.in/verify/MV-CERT-2026-9041?auth=8f4c2e1b',
    createdAt: '2026-02-15T10:00:00Z'
  },
  {
    id: 'CERT-2025-001',
    certificateNumber: 'MV-CERT-2025-4122',
    applicationId: 'APP-2025-0104',
    instrumentId: 'INST-2026-001',
    instrumentName: 'Heavy Duty Pitless Electronic Weighbridge',
    instrumentType: 'Electronic Weighbridge',
    capacity: '60,000 kg x 10 kg',
    accuracyClass: 'Class III (Medium)',
    serialNumber: 'AWT-WB-2023-9981',
    manufacturer: 'Avery Weigh-Tronix India Pvt Ltd',
    modelNumber: 'BridgeMaster Pro-60T',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    installationLocation: 'Main Gate Weigh Station, Plot 44-B, MIDC Industrial Area, Phase II',
    verificationDate: '2025-10-10',
    expiryDate: '2026-10-10',
    officerId: 'usr_officer_1',
    officerName: 'Inspector S. K. Verma',
    officerBadge: 'LMI-DL-2018-044',
    issuingAuthority: 'Department of Legal Metrology, Government of NCT of Delhi',
    jurisdictionZone: 'Industrial Zone 4',
    sealTagNumber: 'DL-LM-SEAL-55102',
    verificationFeePaid: 4500,
    status: 'VALID',
    digitalSignatureHash: 'SHA256:7b11d99ef871020349a1bc40288f61ec9082ac32ef80231908bc129841ab77c1',
    verificationUrl: '/verify/MV-CERT-2025-4122',
    qrPayload: 'https://metroverify360.gov.in/verify/MV-CERT-2025-4122?auth=7b11d99e',
    createdAt: '2025-10-10T12:00:00Z'
  },
  {
    id: 'CERT-2024-001',
    certificateNumber: 'MV-CERT-2024-1090',
    applicationId: 'APP-2024-0018',
    instrumentId: 'INST-2026-005',
    instrumentName: 'High-Speed Inline Checkweigher',
    instrumentType: 'Automatic Catchweigher',
    capacity: '5 kg x 1 g',
    accuracyClass: 'Class III (Medium)',
    serialNumber: 'MT-CW-2023-772',
    manufacturer: 'Mettler Toledo Industrial',
    modelNumber: 'Garvens C3530',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    installationLocation: 'Conveyor Line 2, Packaging Section B, New Delhi',
    verificationDate: '2024-08-01',
    expiryDate: '2025-08-01',
    officerId: 'usr_officer_1',
    officerName: 'Inspector S. K. Verma',
    officerBadge: 'LMI-DL-2018-044',
    issuingAuthority: 'Department of Legal Metrology, Government of NCT of Delhi',
    jurisdictionZone: 'Industrial Zone 4',
    sealTagNumber: 'DL-LM-SEAL-33109',
    verificationFeePaid: 1200,
    status: 'EXPIRED',
    digitalSignatureHash: 'SHA256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    verificationUrl: '/verify/MV-CERT-2024-1090',
    qrPayload: 'https://metroverify360.gov.in/verify/MV-CERT-2024-1090?auth=1a2b3c4d',
    createdAt: '2024-08-01T14:00:00Z'
  },
  {
    id: 'CERT-2024-002',
    certificateNumber: 'MV-CERT-2024-0081',
    applicationId: 'APP-2024-0081',
    instrumentId: 'INST-2026-003',
    instrumentName: 'Old Mechanical Platform Scale',
    instrumentType: 'Platform Scale',
    capacity: '300 kg x 50 g',
    accuracyClass: 'Class III (Medium)',
    serialNumber: 'OLD-PL-2019-11',
    manufacturer: 'National Scale Works',
    modelNumber: 'NSW-300',
    ownerId: 'usr_applicant_1',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    ownerAddress: 'Plot 44-B, MIDC Industrial Area, Phase II, New Delhi',
    installationLocation: 'Scrap Yard, Gate 2',
    verificationDate: '2024-03-10',
    expiryDate: '2025-03-09',
    officerId: 'usr_officer_1',
    officerName: 'Inspector S. K. Verma',
    officerBadge: 'LMI-DL-2018-044',
    issuingAuthority: 'Department of Legal Metrology, Government of NCT of Delhi',
    jurisdictionZone: 'North Delhi Zone 1',
    sealTagNumber: 'DL-LM-SEAL-00129',
    verificationFeePaid: 500,
    status: 'REVOKED',
    revocationReason: 'Lead seal reported cut and replaced without authorization. Show-cause notice served under Section 24 of Legal Metrology Act 2009.',
    revocationDate: '2024-09-15',
    digitalSignatureHash: 'SHA256:ffff1111222233334444555566667777888899990000aaaabbbbccccddddeeee',
    verificationUrl: '/verify/MV-CERT-2024-0081',
    qrPayload: 'https://metroverify360.gov.in/verify/MV-CERT-2024-0081?auth=ffff1111',
    createdAt: '2024-03-10T11:00:00Z'
  }
];

export const INITIAL_RENEWAL_ALERTS: RenewalAlert[] = [
  {
    id: 'REN-001',
    certificateNumber: 'MV-CERT-2025-4122',
    instrumentId: 'INST-2026-001',
    instrumentName: 'Heavy Duty Pitless Electronic Weighbridge',
    instrumentType: 'Electronic Weighbridge',
    serialNumber: 'AWT-WB-2023-9981',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    expiryDate: '2026-10-10',
    daysRemaining: 18,
    status: 'Expiring Soon'
  },
  {
    id: 'REN-002',
    certificateNumber: 'MV-CERT-2024-1090',
    instrumentId: 'INST-2026-005',
    instrumentName: 'High-Speed Inline Checkweigher',
    instrumentType: 'Automatic Catchweigher',
    serialNumber: 'MT-CW-2023-772',
    ownerName: 'Apex Agro & Logistics Hub Ltd',
    expiryDate: '2025-08-01',
    daysRemaining: -417,
    status: 'Expired'
  },
  {
    id: 'REN-003',
    certificateNumber: 'MV-CERT-2025-8890',
    instrumentId: 'INST-2026-007',
    instrumentName: 'Electronic Supermarket Barcode Scale',
    instrumentType: 'Non-Automatic Weighing Instrument (NAWI)',
    serialNumber: 'DIGI-SM-2024-331',
    ownerName: 'Modern Retail Superstores Pvt Ltd',
    expiryDate: '2026-10-02',
    daysRemaining: 10,
    status: 'Due Immediately'
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'NOTIF-001',
    userId: 'usr_applicant_1',
    title: 'Verification Certificate Issued',
    message: 'Your Certificate MV-CERT-2026-9041 for Precision Balance has been digitally approved and is ready for download.',
    type: 'success',
    read: false,
    link: '/applicant/certificates',
    createdAt: '2026-02-15T10:05:00Z'
  },
  {
    id: 'NOTIF-002',
    userId: 'usr_applicant_1',
    title: 'Statutory Reverification Due in 18 Days',
    message: 'Electronic Weighbridge 60T (Certificate MV-CERT-2025-4122) expires on 10-Oct-2026. Submit renewal application to avoid penal action.',
    type: 'warning',
    read: false,
    link: '/applicant/renewal-alerts',
    createdAt: '2026-09-20T08:00:00Z'
  },
  {
    id: 'NOTIF-003',
    userId: 'usr_officer_1',
    title: 'New Inspection Assigned',
    message: 'Application APP-2026-0841 for 60T Weighbridge has been assigned to you. Schedule inspection date.',
    type: 'info',
    read: false,
    link: '/officer/assigned-inspections',
    createdAt: '2026-09-17T11:05:00Z'
  },
  {
    id: 'NOTIF-004',
    userId: 'usr_admin_1',
    title: 'Inspection Completed - Approval Pending',
    message: 'Inspector S. K. Verma has submitted the inspection report for APP-2026-0840 (Fuel Dispenser). Review and issue certificate.',
    type: 'info',
    read: false,
    link: '/admin/approvals',
    createdAt: '2026-09-14T16:05:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-09-22 18:40:12',
    userName: 'Dr. A. Ramanathan (Controller)',
    userRole: 'Administrator',
    action: 'DIGITAL_APPROVAL_QUEUE_VIEWED',
    entityType: 'Application',
    entityId: 'APP-2026-0840',
    details: 'Viewed NAWI inspection summary for Fuel Dispenser prior to certificate signing.',
    ipAddress: '10.14.22.105 (Govt Intranet)',
    status: 'SUCCESS'
  },
  {
    id: 'AUD-002',
    timestamp: '2026-09-18 10:15:33',
    userName: 'Rajesh Sharma',
    userRole: 'Applicant',
    action: 'INSTRUMENT_REGISTERED_APPLICATION_SUBMITTED',
    entityType: 'Instrument',
    entityId: 'INST-2026-004',
    details: 'Submitted online verification application for Bench Platform Scale (150kg x 10g).',
    ipAddress: '115.112.44.89',
    status: 'SUCCESS'
  },
  {
    id: 'AUD-003',
    timestamp: '2026-09-17 11:00:20',
    userName: 'Dr. A. Ramanathan (Controller)',
    userRole: 'Administrator',
    action: 'OFFICER_ASSIGNMENT',
    entityType: 'Application',
    entityId: 'APP-2026-0841',
    details: 'Assigned Inspector S. K. Verma (Badge LMI-DL-2018-044) to 60T Weighbridge.',
    ipAddress: '10.14.22.105',
    status: 'SUCCESS'
  },
  {
    id: 'AUD-004',
    timestamp: '2026-09-14 16:00:48',
    userName: 'Inspector S. K. Verma',
    userRole: 'Verification Officer',
    action: 'FIELD_INSPECTION_SUBMITTED',
    entityType: 'Inspection',
    entityId: 'INSP-2026-001',
    details: 'Uploaded physical, volumetric test and seal DL-LM-SEAL-88402. Result: PASS.',
    ipAddress: '49.36.110.21 (Mobile Inspector App)',
    status: 'SUCCESS'
  },
  {
    id: 'AUD-005',
    timestamp: '2026-02-15 10:00:15',
    userName: 'Dr. A. Ramanathan (Controller)',
    userRole: 'Administrator',
    action: 'CERTIFICATE_ISSUED',
    entityType: 'Certificate',
    entityId: 'MV-CERT-2026-9041',
    details: 'Digital approval granted. QR certificate generated for Class I Gold Balance.',
    ipAddress: '10.14.22.105',
    status: 'SUCCESS'
  }
];
