"""SHAP explainability module generating global and local feature contributions.

DISCLAIMER:
All SHAP attribution scores and explanations generated by this module describe the internal
decision surface of the machine learning model. They represent statistical feature importance
and MUST NOT be cited or presented as statutory or regulatory legal grounds for enforcement.
"""
from pathlib import Path
from typing import Any, Dict, List, Optional
import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap
from src.utils.logger import get_logger

logger = get_logger("shap_explainer")


class MetrologyShapExplainer:
    """Wrapper around SHAP TreeExplainer for Legal Metrology models."""

    def __init__(self, model: Any = None, feature_names: Optional[List[str]] = None):
        self.model = model
        self.feature_names = feature_names or []
        self.explainer: Optional[shap.TreeExplainer] = None

    def fit(self, model: Any, background_sample: Optional[pd.DataFrame] = None) -> "MetrologyShapExplainer":
        """Initializes TreeExplainer with model and optional background sample."""
        self.model = model
        logger.info("Initializing SHAP TreeExplainer...")
        try:
            self.explainer = shap.TreeExplainer(self.model)
        except Exception as e:
            logger.warning(f"Default TreeExplainer failed ({e}). Initializing with background data.")
            self.explainer = shap.TreeExplainer(self.model, data=background_sample)
        logger.info("SHAP TreeExplainer successfully initialized.")
        return self

    def explain_global(
        self,
        X_sample: pd.DataFrame,
        output_dir: Optional[Path | str] = None,
        top_k: int = 15,
    ) -> Dict[str, float]:
        """
        Computes global mean absolute SHAP values across a representative sample,
        saves a summary bar chart, and returns sorted feature importances.
        """
        if self.explainer is None:
            raise RuntimeError("SHAP explainer is not fitted.")

        shap_values = self.explainer.shap_values(X_sample)
        
        # Handle binary classification shapes (list of arrays or 2D array)
        if isinstance(shap_values, list):
            # Binary classification list: [class_0 (PASS), class_1 (FAIL)]
            shap_matrix = shap_values[1] if len(shap_values) > 1 else shap_values[0]
        elif isinstance(shap_values, np.ndarray) and shap_values.ndim == 3:
            shap_matrix = shap_values[:, :, 1]
        else:
            shap_matrix = shap_values

        mean_abs_shap = np.mean(np.abs(shap_matrix), axis=0)
        feature_importance = dict(
            sorted(
                zip(X_sample.columns, [float(x) for x in mean_abs_shap]),
                key=lambda item: item[1],
                reverse=True,
            )
        )

        if output_dir:
            out_p = Path(output_dir)
            out_p.mkdir(parents=True, exist_ok=True)

            top_features = list(feature_importance.keys())[:top_k]
            top_scores = [feature_importance[f] for f in top_features]

            fig, ax = plt.subplots(figsize=(10, 6))
            y_pos = np.arange(len(top_features))
            ax.barh(y_pos, top_scores[::-1], align="center", color="#2ca02c")
            ax.set_yticks(y_pos)
            ax.set_yticklabels(top_features[::-1])
            ax.set_xlabel("Mean |SHAP Value| (Impact on Model Verification Risk)")
            ax.set_title(f"Top {top_k} Features by Global SHAP Importance (Decision Support Only)")
            plt.tight_layout()
            
            plot_path = out_p / "shap_global_feature_importance.png"
            plt.savefig(plot_path, dpi=150)
            plt.close(fig)
            logger.info(f"Saved global SHAP plot to {plot_path}")

        return feature_importance

    def explain_instance(
        self,
        X_single: pd.DataFrame,
        top_k: int = 5,
    ) -> List[Dict[str, Any]]:
        """
        Computes local SHAP explanation for a single record.
        Returns top factors supporting PASS and top factors supporting FAIL.
        """
        if self.explainer is None:
            raise RuntimeError("SHAP explainer is not fitted.")

        shap_values = self.explainer.shap_values(X_single)
        if isinstance(shap_values, list):
            sv = shap_values[1][0] if len(shap_values) > 1 else shap_values[0][0]
        elif isinstance(shap_values, np.ndarray) and shap_values.ndim == 3:
            sv = shap_values[0, :, 1]
        elif isinstance(shap_values, np.ndarray) and shap_values.ndim == 2:
            sv = shap_values[0]
        else:
            sv = shap_values

        features = list(X_single.columns)
        raw_values = X_single.iloc[0].to_dict()

        # Pair features with their SHAP values
        contributions = []
        for feat, s_val in zip(features, sv):
            s_float = float(s_val)
            abs_s = abs(s_float)
            if abs_s > 0.6:
                impact = "high"
            elif abs_s > 0.2:
                impact = "medium"
            else:
                impact = "low"

            # Positive margin in CatBoost binary classifier increases probability of class 1 ('PASS')
            direction = "supports_pass" if s_float > 0 else "supports_fail"
            contributions.append({
                "feature": feat,
                "impact": impact,
                "direction": direction,
                "observed_value": raw_values.get(feat),
                "shap_value": round(s_float, 4),
            })

        # Sort by absolute SHAP impact
        contributions.sort(key=lambda x: abs(x["shap_value"]), reverse=True)
        return contributions[:top_k]

    def save(self, path: Path | str) -> None:
        """Saves explainer object."""
        joblib.dump(self, path)
        logger.info(f"Saved SHAP explainer to {path}")

    @staticmethod
    def load(path: Path | str) -> "MetrologyShapExplainer":
        """Loads fitted explainer from disk."""
        return joblib.load(path)
